version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8083:8083"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/amd64
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8084:80"

  redis:
    image: redis:alpine
    command: ["redis-server", "--requirepass", ""]
    ports:
      - "6379:6379"
